from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest

from train_roll_packet_ocsvm import (
    FEATURE_SETS,
    build_preprocessor,
    build_splits,
    compute_metrics,
    find_f1_optimal_threshold,
    prepare_df,
    resolve_feature_set,
    save_common_outputs,
    set_seed,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--packet-dataset",
        default="artifacts/rolling_fc_address/rolling_packet_features_fc_address.csv",
        help="Packet-level CSV generated by pre_process_rolling_fc_address.py",
    )
    parser.add_argument(
        "--output-dir",
        default="artifacts/rolling_fc_address/packet_results_isolation_forest_per_packet",
        help="Directory for per-packet Isolation Forest outputs.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--feature-set",
        default="packet_full",
        choices=sorted(FEATURE_SETS.keys()),
        help="Which per-packet feature subset to use.",
    )
    parser.add_argument("--n-estimators", type=int, default=300)
    parser.add_argument("--max-samples", default="auto")
    parser.add_argument(
        "--validation-quantile",
        type=float,
        default=0.99,
        help="Quantile of validation anomaly score used as threshold.",
    )
    args = parser.parse_args()

    set_seed(args.seed)

    project_root = Path(__file__).resolve().parents[2]
    dataset_path = project_root / args.packet_dataset
    output_dir = project_root / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(dataset_path)
    df = prepare_df(df)
    train_df, val_df, test_df = build_splits(df)

    feature_columns, categorical_columns, numeric_columns = resolve_feature_set(args.feature_set)
    preprocessor = build_preprocessor(categorical_columns, numeric_columns)
    train_x = preprocessor.fit_transform(train_df[feature_columns])
    val_x = preprocessor.transform(val_df[feature_columns])
    test_x = preprocessor.transform(test_df[feature_columns])

    print(f"Feature dimensions after encoding: {train_x.shape[1]}")
    print(f"Train: {len(train_x)}, Val: {len(val_x)}, Test: {len(test_x)}")

    model = IsolationForest(
        n_estimators=args.n_estimators,
        max_samples=args.max_samples,
        contamination="auto",
        random_state=args.seed,
        n_jobs=-1,
    )
    model.fit(train_x)

    # score_samples: lower = more anomalous. Invert so higher = more anomalous.
    val_scores = -model.score_samples(val_x)
    test_scores = -model.score_samples(test_x)
    val_labels = val_df["is_attack"].astype(int).to_numpy()
    test_labels = test_df["is_attack"].astype(int).to_numpy()

    # --- Method 1: Native boundary (predict == -1 → anomaly) ---
    native_pred = (model.predict(test_x) == -1).astype(int)
    native_metrics = compute_metrics(test_labels, native_pred, test_scores)

    # --- Method 2: Validation quantile threshold [PRIMARY — matches LSTM protocol] ---
    quantile_threshold = float(np.quantile(val_scores, args.validation_quantile))
    quantile_pred = (test_scores >= quantile_threshold).astype(int)
    quantile_metrics = compute_metrics(test_labels, quantile_pred, test_scores)

    # --- Method 3: Val F1-optimal threshold [secondary diagnostic] ---
    val_threshold, val_prec, val_rec, val_f1 = find_f1_optimal_threshold(val_labels, val_scores)
    val_pred = (test_scores >= val_threshold).astype(int)
    val_metrics = compute_metrics(test_labels, val_pred, test_scores)

    # --- Method 4: Test F1-optimal threshold [ORACLE — uses test labels, upper bound only] ---
    oracle_threshold, _, _, _ = find_f1_optimal_threshold(test_labels, test_scores)
    oracle_pred = (test_scores >= oracle_threshold).astype(int)
    oracle_metrics = compute_metrics(test_labels, oracle_pred, test_scores)

    print("\n=== Native boundary (contamination=auto) [no labels] ===")
    print(f"  Precision: {native_metrics['precision']:.4f}")
    print(f"  Recall:    {native_metrics['recall']:.4f}")
    print(f"  F1:        {native_metrics['f1_score']:.4f}")
    print(f"  TP={native_metrics['tp']} FP={native_metrics['fp']} TN={native_metrics['tn']} FN={native_metrics['fn']}")

    print(
        f"\n=== Val quantile threshold p{args.validation_quantile * 100:.0f} "
        f"({quantile_threshold:.4f}) [PRIMARY — matches LSTM protocol] ==="
    )
    print(f"  Precision: {quantile_metrics['precision']:.4f}")
    print(f"  Recall:    {quantile_metrics['recall']:.4f}")
    print(f"  F1:        {quantile_metrics['f1_score']:.4f}")
    print(
        f"  TP={quantile_metrics['tp']} FP={quantile_metrics['fp']} "
        f"TN={quantile_metrics['tn']} FN={quantile_metrics['fn']}"
    )

    print(f"\n=== Val F1-optimal threshold ({val_threshold:.4f}) [secondary diagnostic] ===")
    print(f"  Precision: {val_metrics['precision']:.4f}")
    print(f"  Recall:    {val_metrics['recall']:.4f}")
    print(f"  F1:        {val_metrics['f1_score']:.4f}")
    print(f"  TP={val_metrics['tp']} FP={val_metrics['fp']} TN={val_metrics['tn']} FN={val_metrics['fn']}")

    print(f"\n=== Test oracle threshold ({oracle_threshold:.4f}) [ORACLE — uses test labels, upper bound only] ===")
    print(f"  Precision: {oracle_metrics['precision']:.4f}")
    print(f"  Recall:    {oracle_metrics['recall']:.4f}")
    print(f"  F1:        {oracle_metrics['f1_score']:.4f}")
    print(f"  TP={oracle_metrics['tp']} FP={oracle_metrics['fp']} TN={oracle_metrics['tn']} FN={oracle_metrics['fn']}")

    print(f"\n  AUC: {quantile_metrics['roc_auc']:.4f}")

    metrics_row = {
        "model": "Isolation Forest",
        "threshold_method": "validation_quantile",
        "threshold": quantile_threshold,
        **quantile_metrics,
        "validation_quantile": args.validation_quantile,
        "native_precision": native_metrics["precision"],
        "native_recall": native_metrics["recall"],
        "native_f1": native_metrics["f1_score"],
        "val_f1_threshold": val_threshold,
        "val_f1_precision": val_metrics["precision"],
        "val_f1_recall": val_metrics["recall"],
        "val_f1_f1": val_metrics["f1_score"],
        "oracle_f1_threshold": oracle_threshold,
        "oracle_precision": oracle_metrics["precision"],
        "oracle_recall": oracle_metrics["recall"],
        "oracle_f1": oracle_metrics["f1_score"],
        "n_estimators": args.n_estimators,
        "max_samples": args.max_samples,
        "train_rows": int(len(train_df)),
        "validation_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "feature_set": args.feature_set,
        "feature_columns": ",".join(feature_columns),
        "feature_dims": int(train_x.shape[1]),
    }

    test_scores_df = test_df.reset_index(drop=True).copy()
    test_scores_df["anomaly_score"] = test_scores
    test_scores_df["pred_is_anomaly"] = quantile_pred
    test_scores_df["pred_validation_quantile"] = quantile_pred
    test_scores_df["pred_native"] = native_pred
    test_scores_df["pred_val_f1"] = val_pred
    test_scores_df["pred_oracle_f1"] = oracle_pred
    val_scores_df = val_df.reset_index(drop=True).copy()
    val_scores_df["anomaly_score"] = val_scores

    run_summary = {
        "packet_dataset": str(dataset_path),
        "output_dir": str(output_dir),
        "model": "Isolation Forest",
        "feature_set": args.feature_set,
        "feature_columns": feature_columns,
        "categorical_columns": categorical_columns,
        "numeric_columns": numeric_columns,
        "n_estimators": args.n_estimators,
        "max_samples": args.max_samples,
        "train_rows": int(len(train_df)),
        "validation_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "feature_dims": int(train_x.shape[1]),
        "roc_auc": quantile_metrics["roc_auc"],
        "validation_quantile": args.validation_quantile,
        "validation_quantile_threshold (PRIMARY)": quantile_threshold,
        "validation_quantile_metrics (PRIMARY)": quantile_metrics,
        "val_f1_optimal_threshold": val_threshold,
        "val_f1_optimal_metrics (secondary diagnostic)": val_metrics,
        "native_metrics": native_metrics,
        "oracle_f1_optimal_threshold": oracle_threshold,
        "oracle_f1_optimal_metrics (uses test labels, upper bound only)": oracle_metrics,
    }

    save_common_outputs(
        output_dir=output_dir,
        prefix="packet_isolation_forest",
        test_labels=test_labels,
        test_scores=test_scores,
        test_pred=val_pred,
        metrics_row=metrics_row,
        test_scores_df=test_scores_df,
        val_scores_df=val_scores_df,
        run_summary=run_summary,
    )

    print(f"\nOutputs written to {output_dir}")


if __name__ == "__main__":
    main()
