from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--packet-dataset",
        default="artifacts/fc_address/packet_features_fc_address.csv",
        help="Packet-level CSV generated by pre_process_fc_address.py",
    )
    parser.add_argument(
        "--output-dir",
        default="artifacts/fc_address",
        help="Directory where the window dataset will be written.",
    )
    parser.add_argument(
        "--window-seconds",
        type=float,
        default=1.0,
        help="Window size in seconds.",
    )
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    packet_dataset = project_root / args.packet_dataset
    output_dir = project_root / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(packet_dataset)
    df["pair_token"] = (
        "fc=" + df["function_code"].astype(int).astype(str)
        + "|addr=" + df["address"].astype(int).astype(str)
    )
    df["window_index"] = (df["time_offset_s"] // args.window_seconds).astype(int)

    grouped = (
        df.groupby(["pcap_name", "window_index", "pair_token"])
        .size()
        .rename("count")
        .reset_index()
    )

    window_df = grouped.pivot_table(
        index=["pcap_name", "window_index"],
        columns="pair_token",
        values="count",
        fill_value=0,
    ).reset_index()

    label_df = (
        df.groupby(["pcap_name", "window_index"], as_index=False)
        .agg(
            label=("label", lambda s: "anomaly" if (s != "normal").any() else "normal"),
            is_anomaly=("is_attack", "max"),
            window_start_s=("time_offset_s", "min"),
            window_end_s=("time_offset_s", "max"),
            packet_count=("label", "size"),
        )
    )

    window_df = label_df.merge(window_df, on=["pcap_name", "window_index"], how="left")
    window_df = window_df.sort_values(["pcap_name", "window_index"]).reset_index(drop=True)

    dataset_path = output_dir / "window_features_fc_address.csv"
    window_df.to_csv(dataset_path, index=False)

    summary = {
        "window_seconds": args.window_seconds,
        "row_count": int(len(window_df)),
        "label_counts": window_df["label"].value_counts().to_dict(),
        "pcap_window_counts": window_df.groupby("pcap_name")["window_index"].count().to_dict(),
        "feature_columns": [
            column
            for column in window_df.columns
            if column.startswith("fc=")
        ],
    }
    summary_path = output_dir / "window_preprocess_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(f"Wrote window dataset to {dataset_path}")
    print(f"Wrote summary to {summary_path}")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
