from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd


def build_sequences(
    df: pd.DataFrame,
    feature_columns: list[str],
    sequence_length: int,
) -> tuple[np.ndarray, np.ndarray, list[dict[str, object]]]:
    sequences: list[np.ndarray] = []
    labels: list[int] = []
    metadata: list[dict[str, object]] = []

    for pcap_name, pcap_df in df.groupby("pcap_name"):
        pcap_df = pcap_df.sort_values("window_index").reset_index(drop=True)
        values = pcap_df[feature_columns].to_numpy(dtype=np.float32)
        anomaly_flags = pcap_df["is_anomaly"].to_numpy(dtype=np.int64)
        window_indices = pcap_df["window_index"].to_numpy(dtype=np.int64)
        window_start = pcap_df["window_start_s"].to_numpy(dtype=np.float32)
        window_end = pcap_df["window_end_s"].to_numpy(dtype=np.float32)
        labels_text = pcap_df["label"].to_numpy()

        if len(pcap_df) < sequence_length:
            continue

        for start in range(0, len(pcap_df) - sequence_length + 1):
            end = start + sequence_length
            sequences.append(values[start:end])
            seq_label = int(anomaly_flags[start:end].max())
            labels.append(seq_label)
            metadata.append(
                {
                    "pcap_name": str(pcap_name),
                    "start_window_index": int(window_indices[start]),
                    "end_window_index": int(window_indices[end - 1]),
                    "start_time_s": float(window_start[start]),
                    "end_time_s": float(window_end[end - 1]),
                    "label": "anomaly" if seq_label else "normal",
                    "window_labels": "|".join(str(x) for x in labels_text[start:end]),
                }
            )

    return np.asarray(sequences), np.asarray(labels), metadata


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--window-dataset",
        default="artifacts/fc_address/window_features_fc_address.csv",
        help="Window-level CSV generated by pre_process_fc_address_windows.py",
    )
    parser.add_argument(
        "--output-dir",
        default="artifacts/lstm_fc_address",
        help="Directory where sequence artifacts will be written.",
    )
    parser.add_argument(
        "--sequence-length",
        type=int,
        default=10,
        help="Number of 1-second windows per LSTM sequence.",
    )
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    dataset_path = project_root / args.window_dataset
    output_dir = project_root / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(dataset_path)
    feature_columns = [column for column in df.columns if column.startswith("fc=")]
    sequences, labels, metadata = build_sequences(df, feature_columns, args.sequence_length)

    np.savez_compressed(
        output_dir / "lstm_sequences.npz",
        sequences=sequences,
        labels=labels,
        feature_names=np.array(feature_columns),
    )

    metadata_df = pd.DataFrame(metadata)
    metadata_df.to_csv(output_dir / "lstm_sequence_metadata.csv", index=False)

    summary = {
        "window_dataset": str(dataset_path),
        "sequence_length": args.sequence_length,
        "sequence_count": int(len(sequences)),
        "feature_count": int(len(feature_columns)),
        "label_counts": metadata_df["label"].value_counts().to_dict() if not metadata_df.empty else {},
        "per_pcap_counts": metadata_df.groupby("pcap_name")["pcap_name"].count().to_dict() if not metadata_df.empty else {},
    }
    (output_dir / "lstm_sequence_summary.json").write_text(
        json.dumps(summary, indent=2),
        encoding="utf-8",
    )

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
