from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    auc,
    confusion_matrix,
    precision_recall_fscore_support,
    roc_curve,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--window-dataset",
        default="artifacts/fc_address/window_features_fc_address.csv",
        help="Window-level CSV generated by pre_process_fc_address_windows.py",
    )
    parser.add_argument(
        "--output-dir",
        default="artifacts/fc_address/anomaly",
        help="Directory for anomaly-detection outputs.",
    )
    parser.add_argument(
        "--train-normal-pcaps",
        nargs="*",
        default=["normal_02"],
        help="Pcap names used for normal-only training.",
    )
    parser.add_argument(
        "--validation-normal-pcaps",
        nargs="*",
        default=["normal_03"],
        help="Pcap names used only for threshold calibration.",
    )
    parser.add_argument(
        "--test-pcaps",
        nargs="*",
        default=["attack_write_01", "attack_scan_02"],
        help="Pcap names used only for final testing.",
    )
    parser.add_argument(
        "--validation-quantile",
        type=float,
        default=0.97,
        help="Quantile of validation anomaly score used as threshold.",
    )
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    dataset_path = project_root / args.window_dataset
    output_dir = project_root / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(dataset_path)
    feature_columns = [column for column in df.columns if column.startswith("fc=")]

    train_normal = df[df["pcap_name"].isin(args.train_normal_pcaps)].copy()
    validation_normal = df[df["pcap_name"].isin(args.validation_normal_pcaps)].copy()
    test_df = df[df["pcap_name"].isin(args.test_pcaps)].copy()

    if train_normal.empty or validation_normal.empty or test_df.empty:
        raise ValueError("Train/validation/test split produced an empty dataset. Check pcap names.")

    X_train = train_normal[feature_columns].astype(float)
    X_val = validation_normal[feature_columns].astype(float)
    X_test = test_df[feature_columns].astype(float)
    y_test = test_df["is_anomaly"].astype(int).to_numpy()

    model = IsolationForest(
        n_estimators=300,
        contamination="auto",
        random_state=42,
    )
    model.fit(X_train)

    train_scores = -model.decision_function(X_train)
    val_scores = -model.decision_function(X_val)
    test_scores = -model.decision_function(X_test)
    threshold = float(np.quantile(val_scores, args.validation_quantile))
    y_pred = (test_scores >= threshold).astype(int)

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test,
        y_pred,
        average="binary",
        zero_division=0,
    )
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred, labels=[0, 1]).ravel()

    metrics_df = pd.DataFrame(
        [
            {
                "precision": precision,
                "recall": recall,
                "f1_score": f1,
                "tp": int(tp),
                "fp": int(fp),
                "tn": int(tn),
                "fn": int(fn),
                "threshold": threshold,
                "validation_quantile": args.validation_quantile,
                "train_rows": int(len(train_normal)),
                "validation_rows": int(len(validation_normal)),
                "test_rows": int(len(test_df)),
            }
        ]
    )
    metrics_df.to_csv(output_dir / "anomaly_metrics.csv", index=False)

    cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
    cm_df = pd.DataFrame(cm, index=["normal", "anomaly"], columns=["pred_normal", "pred_anomaly"])
    cm_df.to_csv(output_dir / "anomaly_confusion_matrix.csv")

    plt.figure(figsize=(5, 4))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["normal", "anomaly"])
    disp.plot(cmap="Blues", values_format="d")
    plt.title("Anomaly Confusion Matrix")
    plt.tight_layout()
    plt.savefig(output_dir / "anomaly_confusion_matrix.png", dpi=200)
    plt.close()

    fpr, tpr, _ = roc_curve(y_test, test_scores)
    roc_auc = float(auc(fpr, tpr))
    plt.figure(figsize=(6, 4.5))
    plt.plot(fpr, tpr, label=f"AUC={roc_auc:.3f}")
    plt.plot([0, 1], [0, 1], linestyle="--", color="gray")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("Anomaly ROC Curve")
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_dir / "anomaly_roc_curve.png", dpi=200)
    plt.close()

    scored_df = test_df[
        ["pcap_name", "window_index", "window_start_s", "window_end_s", "label", "is_anomaly", "packet_count"]
    ].copy()
    scored_df["anomaly_score"] = test_scores
    scored_df["pred_is_anomaly"] = y_pred
    scored_df.to_csv(output_dir / "window_scores.csv", index=False)

    run_summary = {
        "window_dataset": str(dataset_path),
        "output_dir": str(output_dir),
        "feature_count": len(feature_columns),
        "train_normal_pcaps": args.train_normal_pcaps,
        "validation_normal_pcaps": args.validation_normal_pcaps,
        "test_pcaps": args.test_pcaps,
        "train_rows": int(len(train_normal)),
        "validation_rows": int(len(validation_normal)),
        "test_rows": int(len(test_df)),
        "threshold": threshold,
        "validation_quantile": args.validation_quantile,
        "roc_auc": roc_auc,
    }
    (output_dir / "run_summary.json").write_text(json.dumps(run_summary, indent=2), encoding="utf-8")

    print(metrics_df.to_string(index=False))
    print(f"ROC AUC: {roc_auc:.4f}")
    print(f"Outputs written to {output_dir}")


if __name__ == "__main__":
    main()
