from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from lstm_window_common import (
    PROJECT_ROOT,
    build_fixed_train_windows,
    build_packet_samples,
    build_test_samples_with_context,
    build_token_mapping,
    compute_metrics_at_threshold,
    compute_threshold_from_scores,
    contiguous_attack_segments,
    filter_packet_rows,
    fit_model,
    plot_metrics,
    plot_thresholds,
    prepare_run,
    resolve_device,
    score_samples,
    set_seed,
    smooth_scores,
    anomaly_scores,
)
from packet_roll_transformer import PacketRollTransformer


def build_parser(description: str) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument(
        "--packet-dataset",
        default="artifacts/rolling_fc_address_port_protocol/rolling_packet_features_fc_address.csv",
        help="Packet-level rolling CSV generated by preprocessing.",
    )
    parser.add_argument(
        "--output-dir",
        default="artifacts/transformer_fixed_results",
        help="Directory for fixed-train Transformer outputs.",
    )
    parser.add_argument("--pcap-name", default="mixed_long_conti")
    parser.add_argument(
        "--fixed-train-end-s",
        type=float,
        required=True,
        help="Train once on [0, fixed_train_end_s], then slide only the test window.",
    )
    parser.add_argument("--test-duration-s", type=float, default=300.0)
    parser.add_argument("--step-s", type=float, default=120.0)
    parser.add_argument("--val-fraction", type=float, default=0.2)
    parser.add_argument(
        "--oracle-clean-normal-only",
        action="store_true",
        help="Diagnostic mode: filter attack-labeled packets out of the training and validation slices.",
    )
    parser.add_argument("--context-length", type=int, default=30)
    parser.add_argument("--smooth-window", type=int, default=30)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--score-batch-size", type=int, default=1024)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--model-dim", type=int, default=32)
    parser.add_argument("--num-heads", type=int, default=4)
    parser.add_argument("--ffn-dim", type=int, default=128)
    parser.add_argument("--num-layers", type=int, default=2)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--patience", type=int, default=10)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--validation-quantile", type=float, default=0.95)
    parser.add_argument(
        "--threshold-method",
        default="sigma",
        choices=["quantile", "sigma", "test_quantile"],
        help="'sigma' sets threshold = mean + k*std of calibration scores; "
        "'quantile' uses the validation quantile; "
        "'test_quantile' sets a per-test-window threshold.",
    )
    parser.add_argument(
        "--threshold-sigma",
        type=float,
        default=4.0,
        help="Number of standard deviations above the calibration mean (--threshold-method sigma only).",
    )
    parser.add_argument(
        "--test-anomaly-quantile",
        type=float,
        default=0.99,
        help="Quantile of test scores used as threshold when --threshold-method test_quantile.",
    )
    parser.add_argument(
        "--exclude-tcp-fc-minus1",
        action="store_true",
        help="Drop packets where protocol == TCP and function_code == -1 before building windows.",
    )
    return parser


def create_model(args: argparse.Namespace) -> PacketRollTransformer:
    return PacketRollTransformer(
        vocab_size=args.vocab_size,
        model_dim=args.model_dim,
        num_heads=args.num_heads,
        ffn_dim=args.ffn_dim,
        num_layers=args.num_layers,
        dropout=args.dropout,
        max_context_length=args.context_length,
    ).to(resolve_device())


def plot_score_timeline(
    scores_df: pd.DataFrame,
    attack_segments: list[tuple[float, float, str]],
    output_path: Path,
) -> None:
    if scores_df.empty:
        return

    aggregated = (
        scores_df.groupby("time_offset_s", as_index=False)
        .agg(anomaly_score=("anomaly_score", "mean"), threshold=("threshold", "mean"))
        .sort_values("time_offset_s")
    )

    plt.figure(figsize=(12, 5))
    plt.plot(aggregated["time_offset_s"], aggregated["anomaly_score"], label="mean anomaly score", linewidth=1.2)
    plt.plot(aggregated["time_offset_s"], aggregated["threshold"], label="mean threshold", linewidth=1.0, linestyle="--")
    for start_s, end_s, label in attack_segments:
        plt.axvspan(start_s, end_s, alpha=0.18, color="tomato")
        plt.text(start_s, plt.ylim()[1] * 0.95, label, fontsize=8, va="top")
    plt.xlabel("time_offset_s")
    plt.ylabel("anomaly score")
    plt.title("Fixed-Train Packet Transformer Score Timeline")
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=200)
    plt.close()


def write_outputs(
    *,
    dataset_path: Path,
    output_dir: Path,
    df: pd.DataFrame,
    windows: list[dict[str, float]],
    metrics_rows: list[dict[str, Any]],
    scores_df: pd.DataFrame,
    last_train_losses: list[float],
    last_val_losses: list[float],
    token_to_idx: dict[str, int],
    filter_summary: dict[str, int],
    args: argparse.Namespace,
) -> None:
    metrics_df = pd.DataFrame(metrics_rows)
    ok_metrics_df = metrics_df[metrics_df["status"] == "ok"] if "status" in metrics_df else pd.DataFrame()

    metrics_path = output_dir / "sliding_window_step_metrics.csv"
    scores_path = output_dir / "sliding_window_all_scores.csv"
    metrics_df.to_csv(metrics_path, index=False)
    scores_df.to_csv(scores_path, index=False)

    attack_segments = contiguous_attack_segments(df)
    plot_score_timeline(scores_df, attack_segments, output_dir / "sliding_window_score_timeline.png")
    plot_metrics(ok_metrics_df, output_dir / "sliding_window_metrics_over_time.png")
    plot_thresholds(ok_metrics_df, output_dir / "sliding_window_threshold_over_time.png")

    if last_train_losses and last_val_losses:
        plt.figure(figsize=(7, 4))
        epochs = np.arange(1, len(last_train_losses) + 1)
        plt.plot(epochs, last_train_losses, label="train_loss")
        plt.plot(epochs, last_val_losses, label="val_loss")
        plt.xlabel("epoch")
        plt.ylabel("loss")
        plt.title("Last Transformer Training Curve")
        plt.legend()
        plt.tight_layout()
        plt.savefig(output_dir / "sliding_window_last_training_curve.png", dpi=200)
        plt.close()

    threshold_calibration_mode = "test_quantile" if args.threshold_method == "test_quantile" else "fixed_train"
    run_summary = {
        "packet_dataset": str(dataset_path),
        "output_dir": str(output_dir),
        "pcap_name": args.pcap_name,
        "execution_mode": "fixed_train_transformer",
        "window_count": int(len(windows)),
        "successful_window_count": int((metrics_df["status"] == "ok").sum()) if "status" in metrics_df else 0,
        "fixed_train_end_s": float(args.fixed_train_end_s),
        "test_duration_s": float(args.test_duration_s),
        "step_s": float(args.step_s),
        "val_fraction": float(args.val_fraction),
        "oracle_clean_normal_only": bool(args.oracle_clean_normal_only),
        "context_length": int(args.context_length),
        "smooth_window": int(args.smooth_window),
        "validation_quantile": float(args.validation_quantile),
        "test_anomaly_quantile": float(args.test_anomaly_quantile),
        "threshold_calibration_mode": threshold_calibration_mode,
        "threshold_calibration_split": "test_window" if args.threshold_method == "test_quantile" else "window_validation",
        "model_dim": int(args.model_dim),
        "num_heads": int(args.num_heads),
        "ffn_dim": int(args.ffn_dim),
        "num_layers": int(args.num_layers),
        "dropout": float(args.dropout),
        "vocab_size": len(token_to_idx),
        "exclude_tcp_fc_minus1": bool(args.exclude_tcp_fc_minus1),
        **filter_summary,
    }
    (output_dir / "run_summary.json").write_text(json.dumps(run_summary, indent=2), encoding="utf-8")

    print(f"Wrote metrics to {metrics_path}")
    print(f"Wrote scores to {scores_path}")
    print(json.dumps(run_summary, indent=2))
